language: node_js
node_js:
  - "stable"
env:
  - NODE_ENV="test"
services:
  - "postgresql"
addons:
  postgresql: "9.6"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database insta_dev_test;' -U postgres
script:
  - npm test