language: node_js
node_js:
  - "stable"
env:
  - NODE_ENV="test"
services:
  - "postgresql"
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database insta_dev_test;' -U postgres
  - knex migrate:latest interactions & sleep 2
  - knex migrate:rollback interactions
  - knex migrate:latest interactions
  - node database/seed-testdb.js & sleep 3
  - node server/index.js & sleep 5
script:
  - npm test